#!/usr/bin/env python3
"""Maltese A1 and Swadesh vocabulary seeds for minicloze."""

from __future__ import annotations

SWADESH_SOURCE = "Wiktionary Maltese Swadesh seed"
A1_SOURCE = "LLM-curated Maltese A1 seed list 2026-10-06"
BATCH_SOURCE_A1 = "LLM-authored Maltese A1 2026-10-06"
BATCH_SOURCE_SWADESH = "LLM-authored Maltese Swadesh 2026-10-06"

# English Swadesh glosses (standard 207).
SWADESH_GLOSSES = [
    "i", "you", "he", "we", "you", "they", "this", "that", "here", "there",
    "who", "what", "where", "when", "how", "not", "all", "many", "some", "few",
    "other", "one", "two", "three", "four", "five", "big", "long", "wide", "thick",
    "heavy", "small", "short", "narrow", "thin", "woman", "man", "person", "child", "wife",
    "husband", "mother", "father", "animal", "fish", "bird", "dog", "louse", "snake", "worm",
    "tree", "forest", "stick", "fruit", "seed", "leaf", "root", "bark", "flower", "grass",
    "rope", "skin", "meat", "blood", "bone", "fat", "egg", "horn", "tail", "feather",
    "hair", "head", "ear", "eye", "nose", "mouth", "tooth", "tongue", "nail", "foot",
    "leg", "knee", "hand", "wing", "belly", "guts", "neck", "back", "breast", "heart",
    "liver", "drink", "eat", "bite", "suck", "spit", "vomit", "blow", "breathe", "laugh",
    "see", "hear", "know", "think", "smell", "fear", "sleep", "live", "die", "kill",
    "fight", "hunt", "hit", "cut", "split", "stab", "scratch", "dig", "swim", "fly",
    "walk", "come", "lie", "sit", "stand", "turn", "fall", "give", "hold", "squeeze",
    "rub", "wash", "wipe", "pull", "push", "throw", "tie", "sew", "count", "say",
    "sing", "play", "float", "flow", "freeze", "swell", "sun", "moon", "star", "water",
    "rain", "river", "lake", "sea", "salt", "stone", "sand", "dust", "earth", "cloud",
    "fog", "sky", "wind", "snow", "ice", "smoke", "fire", "ash", "burn", "road",
    "mountain", "red", "green", "yellow", "white", "black", "night", "day", "year", "warm",
    "cold", "full", "new", "old", "good", "bad", "rotten", "dirty", "straight", "round",
    "sharp", "dull", "smooth", "wet", "dry", "right", "near", "far", "right", "left",
    "at", "in", "with", "and", "if", "because", "name",
]

# Preferred modern Maltese forms (index 1-based). Documented overrides vs raw Wiktionary.
SWADESH_WORDS = [
    "jien", "int", "hu", "aħna", "intom", "huma", "dan", "dak", "hawn", "hemm",
    "min", "x'inhu", "fejn", "meta", "kif", "mhux", "kull", "ħafna", "xi", "ftit",
    "ieħor", "wieħed", "tnejn", "tlieta", "erbgħa", "ħamsa", "kbir", "twil", "wiesa'", "oħxon",
    "tqil", "żgħir", "qasir", "dejjaq", "irqiq", "mara", "raġel", "bniedem", "tifel", "mara",
    "raġel", "omm", "missier", "annimal", "ħut", "għasfur", "kelb", "qamla", "serp", "dudu",
    "siġra", "foresta", "bastun", "frott", "żerriegħa", "werqa", "għerq", "qoxra", "fjura", "ħaxix",
    "ħabel", "ġilda", "laħam", "demm", "għadma", "xaħam", "bajda", "qarn", "denb", "rixa",
    "xagħar", "ras", "widna", "għajn", "mnieħer", "ħalq", "sinna", "lsien", "difer", "sieq",
    "riġel", "rkoppa", "id", "ġewnaħ", "żaqq", "msaren", "għonq", "dahar", "sider", "qalb",
    "fwied", "xorob", "kiel", "gidem", "reda'", "beżaq", "qala'", "nefaħ", "ħa nifs", "daħaq",
    "ra", "sema'", "jaf", "ħaseb", "xamm", "beża'", "raqad", "għex", "miet", "qatel",
    "ġġieled", "kkaċċja", "laqat", "qata'", "qasam", "ġerraħ", "barax", "ħaffer", "għam", "tar",
    "mexa", "ġie", "mtedd", "poġġa", "waqaf", "dar", "waqa'", "ta", "żamm", "għafas",
    "ħakk", "ħasel", "mesaħ", "ġibed", "deffes", "rema", "rabat", "ħiet", "għadd", "qal",
    "kanta", "lagħab", "żamm fil-wiċċ", "ġera", "ffriża", "żżembaħ", "xemx", "qamar", "stilla", "ilma",
    "xita", "xmara", "għadira", "baħar", "melħ", "ġebla", "ramel", "trab", "art", "sħaba",
    "ċpar", "sema", "riħ", "borra", "silġ", "duħħan", "nar", "rmied", "ħaraq", "triq",
    "muntanja", "aħmar", "aħdar", "isfar", "abjad", "iswed", "lejl", "jum", "sena", "sħun",
    "kiesaħ", "mimli", "ġdid", "qadim", "tajjeb", "ħażin", "mħassar", "maħmuġ", "dritt", "tond",
    "qattiegħi", "ċatt", "lixx", "mxarrab", "niexef", "korrett", "ħdejn", "bogħod", "lemin", "xellug",
    "għand", "fi", "ma'", "u", "jekk", "għax", "isem",
]

SWADESH_OVERRIDES_NOTES = {
    12: "x'inhu (common 'what is it' form; Wiktionary also lists għal xiex / x')",
    23: "tnejn (cardinal; Wiktionary also żewġ as construct)",
    38: "bniedem (person/human)",
    53: "bastun (stick)",
    59: "fjura (flower; Wiktionary also warda)",
    89: "sider (breast/chest)",
    111: "ġġieled (fight)",
    117: "barax (scratch)",
    141: "kanta (sing; common modern form)",
    143: "żamm fil-wiċċ (float)",
    145: "ffriża (freeze; common loan)",
    149: "stilla (star)",
    156: "ġebla (stone)",
    159: "art (earth/ground)",
    164: "borra (snow; Wiktionary lists silġ/borra — silġ kept for ice)",
    178: "jum (day)",
    184: "qadim (old)",
    192: "ċatt (dull/blunt; Wiktionary entry empty)",
    195: "niexef (dry)",
    196: "korrett (right/correct; distinct from tajjeb)",
    199: "lemin (right side; distinct from korrett)",
    202: "fi (in; fuller form of f')",
    203: "ma' (with)",
}

# category hints for swadesh indices (1-based), coarse
def swadesh_category(index: int, gloss: str) -> str:
    g = gloss.lower()
    if index <= 6:
        return "pronoun"
    if index in {7, 8, 9, 10}:
        return "deictic"
    if index in {11, 12, 13, 14, 15}:
        return "question"
    if index == 16:
        return "negation"
    if index in {17, 18, 19, 20, 21} or g in {"and", "if", "because", "with", "in", "at", "near", "far", "left", "right"} and index >= 197:
        if index >= 197:
            return "function"
        return "function"
    if 22 <= index <= 26:
        return "number"
    if index in {27, 28, 29, 30, 31, 32, 33, 34, 35, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196}:
        return "adjective"
    if 36 <= index <= 43:
        return "person"
    if 44 <= index <= 50:
        return "animal"
    if 51 <= index <= 61 or 147 <= index <= 171:
        return "nature"
    if 62 <= index <= 91:
        return "body"
    if 92 <= index <= 146 or index == 169:
        return "verb"
    if 172 <= index <= 176:
        return "color"
    if index in {177, 178, 179}:
        return "time"
    if index == 207:
        return "object"
    return "object"


A1_EXTRAS: list[tuple[str, str, str]] = [
    # phrases / greetings
    ("bonġu", "hello", "phrase"),
    ("jekk jogħġbok", "please", "phrase"),
    ("grazzi", "thank you", "phrase"),
    ("skużani", "sorry", "phrase"),
    ("ċaw", "goodbye", "phrase"),
    ("iva", "yes", "phrase"),
    ("le", "no", "phrase"),
    ("ok", "okay", "adjective"),
    ("merħba", "welcome", "phrase"),
    ("bonġu għalik", "good morning", "phrase"),
    ("bongu", "good day", "phrase"),
    ("bonswa", "good evening", "phrase"),
    ("il-lejl it-tajjeb", "good night", "phrase"),
    ("kif inti", "how are you", "phrase"),
    ("tajjeb ħafna", "very well", "phrase"),
    # people
    ("ħabib", "friend", "person"),
    ("familja", "family", "person"),
    ("nanna", "grandmother", "person"),
    ("nannu", "grandfather", "person"),
    ("oħt", "sister", "person"),
    ("ħu", "brother", "person"),
    ("ziju", "uncle", "person"),
    ("zija", "aunt", "person"),
    ("ġar", "neighbor", "person"),
    ("għalliem", "teacher", "person"),
    ("student", "student", "person"),
    ("skular", "pupil", "person"),
    ("tabib", "doctor", "person"),
    ("infermier", "nurse", "person"),
    ("pulizija", "police officer", "person"),
    ("sewwieq", "driver", "person"),
    ("ħaddiem", "worker", "person"),
    ("bejjiegħ", "seller", "person"),
    ("klijent", "customer", "person"),
    ("mistednin", "guest", "person"),
    ("tifla", "girl", "person"),
    ("subien", "boys", "person"),
    ("wild", "son or daughter", "person"),
    ("iben", "son", "person"),
    ("bint", "daughter", "person"),
    ("ġenitur", "parent", "person"),
    ("qarib", "relative", "person"),
    ("imgħallem", "boss", "person"),
    ("kollega", "colleague", "person"),
    ("tfajla", "young woman", "person"),
    ("żagħżugħ", "young man", "person"),
    ("tarbija", "baby", "person"),
    ("ħabiba", "female friend", "person"),
    # places
    ("dar", "house", "place"),
    ("skola", "school", "place"),
    ("suq", "market", "place"),
    ("ħanut", "shop", "place"),
    ("triq", "street", "place"),
    ("belt", "city", "place"),
    ("raħal", "village", "place"),
    ("lukanda", "hotel", "place"),
    ("bank", "bank", "place"),
    ("sptar", "hospital", "place"),
    ("spiżerija", "pharmacy", "place"),
    ("park", "park", "place"),
    ("waqfa", "stop", "place"),
    ("stazzjon", "station", "place"),
    ("uffiċċju", "office", "place"),
    ("restorant", "restaurant", "place"),
    ("kafé", "cafe", "place"),
    ("mużew", "museum", "place"),
    ("librerija", "library", "place"),
    ("kamra", "room", "place"),
    ("kamra tas-sodda", "bedroom", "place"),
    ("kċina", "kitchen", "place"),
    ("banju", "bathroom", "place"),
    ("bitħa", "yard", "place"),
    ("pont", "bridge", "place"),
    ("knisja", "church", "place"),
    ("università", "university", "place"),
    ("fabbrika", "factory", "place"),
    ("pjazza", "square", "place"),
    ("ajruport", "airport", "place"),
    ("posta", "post office", "place"),
    ("klassi", "classroom", "place"),
    ("pixxina", "pool", "place"),
    ("teatru", "theater", "place"),
    ("ċinema", "cinema", "place"),
    ("bajja", "beach", "place"),
    ("ġnien", "garden", "place"),
    ("żoo", "zoo", "place"),
    ("garage", "garage", "place"),
    ("bitħa tal-iskola", "schoolyard", "place"),
    ("sala", "hall", "place"),
    # time
    ("illum", "today", "time"),
    ("għada", "tomorrow", "time"),
    ("ilbieraħ", "yesterday", "time"),
    ("issa", "now", "time"),
    ("għodwa", "morning", "time"),
    ("nofsinhar", "noon", "time"),
    ("filgħaxija", "evening", "time"),
    ("ġimgħa", "week", "time"),
    ("xahar", "month", "time"),
    ("siegħa", "hour", "time"),
    ("minuta", "minute", "time"),
    ("it-tnejn", "Monday", "time"),
    ("it-tlieta", "Tuesday", "time"),
    ("l-erbgħa", "Wednesday", "time"),
    ("il-ħamis", "Thursday", "time"),
    ("il-ġimgħa", "Friday", "time"),
    ("is-sibt", "Saturday", "time"),
    ("il-ħadd", "Sunday", "time"),
    ("Jannar", "January", "time"),
    ("Frar", "February", "time"),
    ("Marzu", "March", "time"),
    ("April", "April", "time"),
    ("Mejju", "May", "time"),
    ("Ġunju", "June", "time"),
    ("Lulju", "July", "time"),
    ("Awwissu", "August", "time"),
    ("Settembru", "September", "time"),
    ("Ottubru", "October", "time"),
    ("Novembru", "November", "time"),
    ("Diċembru", "December", "time"),
    ("dalwaqt", "soon", "time"),
    ("dejjem", "always", "time"),
    ("qatt", "never", "time"),
    ("spiss", "often", "time"),
    ("kultant", "sometimes", "time"),
    # food / drink
    ("ħobż", "bread", "food"),
    ("kafè", "coffee", "drink"),
    ("te", "tea", "drink"),
    ("ħalib", "milk", "drink"),
    ("zokkor", "sugar", "food"),
    ("ross", "rice", "food"),
    ("għaġin", "pasta", "food"),
    ("soppa", "soup", "food"),
    ("ħaxix", "vegetables", "food"),
    ("banana", "banana", "food"),
    ("larinġa", "orange", "food"),
    ("tuffieħa", "apple", "food"),
    ("patata", "potato", "food"),
    ("tadam", "tomato", "food"),
    ("basal", "onion", "food"),
    ("butir", "butter", "food"),
    ("għasel", "honey", "food"),
    ("ġobon", "cheese", "food"),
    ("insalata", "salad", "food"),
    ("kolazzjoni", "breakfast", "food"),
    ("ikel", "food", "food"),
    ("ikla", "meal", "food"),
    ("ġelat", "ice cream", "food"),
    ("meraq", "juice", "drink"),
    ("jogurt", "yogurt", "food"),
    ("sandwich", "sandwich", "food"),
    ("ħjara", "cucumber", "food"),
    ("zunnarija", "carrot", "food"),
    ("frawli", "strawberry", "food"),
    ("lumi", "lemon", "food"),
    ("kejk", "cake", "food"),
    ("pizza", "pizza", "food"),
    ("ħut moqli", "fried fish", "food"),
    ("pastizzi", "pastizzi", "food"),
    ("ftira", "ftira bread", "food"),
    ("ilma minerali", "mineral water", "drink"),
    ("inbid", "wine", "drink"),
    ("birra", "beer", "drink"),
    # objects
    ("ktieb", "book", "object"),
    ("notebook", "notebook", "object"),
    ("pinna", "pen", "object"),
    ("lapes", "pencil", "object"),
    ("mejda", "table", "object"),
    ("siġġu", "chair", "object"),
    ("sodda", "bed", "object"),
    ("bieb", "door", "object"),
    ("tieqa", "window", "object"),
    ("ċavetta", "key", "object"),
    ("telefon", "phone", "object"),
    ("kompjuter", "computer", "object"),
    ("televixin", "television", "object"),
    ("radju", "radio", "object"),
    ("borża", "bag", "object"),
    ("ħwejjeġ", "clothes", "object"),
    ("żraben", "shoes", "object"),
    ("kappell", "hat", "object"),
    ("qmis", "shirt", "object"),
    ("qliezet", "pants", "object"),
    ("libsa", "dress", "object"),
    ("ġakketta", "jacket", "object"),
    ("flus", "money", "object"),
    ("euro", "euro", "object"),
    ("biljett", "ticket", "object"),
    ("mappa", "map", "object"),
    ("rigal", "gift", "object"),
    ("kaxxa", "box", "object"),
    ("sapun", "soap", "object"),
    ("xugaman", "towel", "object"),
    ("mera", "mirror", "object"),
    ("tazza", "cup", "object"),
    ("platt", "plate", "object"),
    ("mgħarfa", "spoon", "object"),
    ("sikkina", "knife", "object"),
    ("furketta", "fork", "object"),
    ("lezzjoni", "lesson", "object"),
    ("xogħol", "work", "object"),
    ("homework", "homework", "object"),
    ("eżami", "exam", "object"),
    ("mistoqsija", "question", "object"),
    ("tweġiba", "answer", "object"),
    ("ittra", "letter", "object"),
    ("email", "email", "object"),
    ("ritratt", "photo", "object"),
    ("gazzetta", "newspaper", "object"),
    ("arloġġ", "clock", "object"),
    ("lampa", "lamp", "object"),
    ("bottilja", "bottle", "object"),
    ("umbrella", "umbrella", "object"),
    (" mill-ġdid", "again", "function"),  # will clean
    # transport
    ("karozza", "car", "transport"),
    ("xarabank", "bus", "transport"),
    ("ferrovija", "train", "transport"),
    ("taksi", "taxi", "transport"),
    ("ajruplan", "airplane", "transport"),
    ("dgħajsa", "boat", "transport"),
    ("rota", "bicycle", "transport"),
    ("mutur", "motorcycle", "transport"),
    ("metro", "metro", "transport"),
    ("vapur", "ship", "transport"),
    ("scooter", "scooter", "transport"),
    # animals extras
    ("qattus", "cat", "animal"),
    ("żiemel", "horse", "animal"),
    ("baqra", "cow", "animal"),
    ("nagħġa", "sheep", "animal"),
    ("ħanżir", "pig", "animal"),
    ("fenek", "rabbit", "animal"),
    ("farfett", "butterfly", "animal"),
    ("naħla", "bee", "animal"),
    ("wiżża", "goose", "animal"),
    ("papra", "duck", "animal"),
    ("fniek", "rabbits", "animal"),
    ("ħamiem", "pigeon", "animal"),
    # adjectives extras
    ("sabiħ", "beautiful", "adjective"),
    ("ikrah", "ugly", "adjective"),
    ("faċli", "easy", "adjective"),
    ("diffiċli", "difficult", "adjective"),
    ("mgħaġġel", "fast", "adjective"),
    ("bil-mod", "slow", "adjective"),
    ("qawwi", "strong", "adjective"),
    ("dgħajjef", "weak", "adjective"),
    ("ferħan", "happy", "adjective"),
    ("imdejjaq", "sad", "adjective"),
    ("għajjien", "tired", "adjective"),
    ("bil-ġuħ", "hungry", "adjective"),
    ("bil-għatx", "thirsty", "adjective"),
    ("morda", "sick", "adjective"),
    ("b'saħħtu", "healthy", "adjective"),
    ("għali", "expensive", "adjective"),
    ("irħis", "cheap", "adjective"),
    ("nadif", "clean", "adjective"),
    ("miftuħ", "open", "adjective"),
    ("magħluq", "closed", "adjective"),
    ("vojt", "empty", "adjective"),
    ("okkupat", "busy", "adjective"),
    ("liberu", "free", "adjective"),
    ("importante", "important", "adjective"),
    ("perikoluż", "dangerous", "adjective"),
    ("sikur", "safe", "adjective"),
    ("qrib", "close", "adjective"),
    ("għoli", "tall", "adjective"),
    ("baxx", "low", "adjective"),
    ("fond", "deep", "adjective"),
    ("ċar", "clear", "adjective"),
    ("skur", "dark", "adjective"),
    ("ħelu", "sweet", "adjective"),
    ("qares", "sour", "adjective"),
    ("mielaħ", "salty", "adjective"),
    ("frisk", "fresh", "adjective"),
    # colors extras
    ("blu", "blue", "color"),
    ("roża", "pink", "color"),
    ("kannella", "brown", "color"),
    ("griż", "gray", "color"),
    ("vjola", "purple", "color"),
    ("oranġjo", "orange color", "color"),
    # verbs / everyday
    ("ried", "want", "verb"),
    ("seta'", "can", "verb"),
    ("għamel", "do", "verb"),
    ("mar", "go", "verb"),
    ("ħa", "take", "verb"),
    ("ġieb", "bring", "verb"),
    ("fetaħ", "open", "verb"),
    ("għalaq", "close", "verb"),
    ("kiteb", "write", "verb"),
    ("qara", "read", "verb"),
    ("tgħallem", "learn", "verb"),
    ("għallem", "teach", "verb"),
    ("ħadem", "work", "verb"),
    ("studja", "study", "verb"),
    ("xtara", "buy", "verb"),
    ("biegħ", "sell", "verb"),
    ("ħallas", "pay", "verb"),
    ("saq", "drive", "verb"),
    ("stenna", "wait", "verb"),
    ("għin", "help", "verb"),
    ("ħobb", "love", "verb"),
    ("xtaq", "wish", "verb"),
    ("beda", "start", "verb"),
    ("temm", "finish", "verb"),
    ("qam", "get up", "verb"),
    ("libes", "wear", "verb"),
    ("neża'", "take off", "verb"),
    ("sajjar", "cook", "verb"),
    ("qata' l-ħaxix", "cut vegetables", "verb"),
    ("ċempel", "call", "verb"),
    ("wieġeb", "answer", "verb"),
    ("saqsa", "ask", "verb"),
    ("fisser", "explain", "verb"),
    ("ftakar", "remember", "verb"),
    ("nesa", "forget", "verb"),
    ("emmen", "believe", "verb"),
    ("ttama", "hope", "verb"),
    ("ħares", "look", "verb"),
    ("sama'", "listen", "verb"),
    ("tkellem", "speak", "verb"),
    ("fehem", "understand", "verb"),
    ("traduċa", "translate", "verb"),
    ("żar", "visit", "verb"),
    ("ivvjaġġa", "travel", "verb"),
    ("żifen", "dance", "verb"),
    ("pinġa", "draw", "verb"),
    ("żelaq", "slip", "verb"),
    ("ġera", "run", "verb"),
    ("qabeż", "jump", "verb"),
    ("waqa' bilqiegħda", "sit down", "verb"),
    ("tela'", "go up", "verb"),
    ("niżel", "go down", "verb"),
    ("daħal", "enter", "verb"),
    ("ħareġ", "exit", "verb"),
    ("wasal", "arrive", "verb"),
    ("telaq", "leave", "verb"),
    ("irritorna", "return", "verb"),
    ("sab", "find", "verb"),
    ("tilef", "lose", "verb"),
    ("żamm", "keep", "verb"),
    ("beda jikteb", "begin writing", "verb"),
    # function / misc
    ("imma", "but", "function"),
    ("jew", "or", "function"),
    ("għalhekk", "therefore", "function"),
    ("qabel", "before", "function"),
    ("wara", "after", "function"),
    ("mingħajr", "without", "function"),
    ("bħal", "like", "function"),
    ("dwar", "about", "function"),
    ("bejn", "between", "function"),
    ("fuq", "on", "function"),
    ("taħt", "under", "function"),
    ("ġewwa", "inside", "function"),
    ("barra", "outside", "function"),
    ("wisq", "too much", "function"),
    ("biżżejjed", "enough", "function"),
    ("biss", "only", "function"),
    ("ukoll", "also", "function"),
    ("diġà", "already", "function"),
    ("għad", "still", "function"),
    ("forsi", "maybe", "function"),
    ("żgur", "surely", "function"),
    ("verament", "really", "function"),
    # numbers extras
    ("sitta", "six", "number"),
    ("sebgħa", "seven", "number"),
    ("tmienja", "eight", "number"),
    ("disgħa", "nine", "number"),
    ("għaxra", "ten", "number"),
    ("ħdax", "eleven", "number"),
    ("tnax", "twelve", "number"),
    ("għoxrin", "twenty", "number"),
    ("mitejn", "two hundred", "number"),
    ("elf", "thousand", "number"),
    # body extras
    ("wiċċ", "face", "body"),
    ("spalla", "shoulder", "body"),
    ("driegħ", "arm", "body"),
    ("suba'", "finger", "body"),
    ("bżar", "pepper", "food"),
    ("melħ tal-mejda", "table salt", "food"),
    ("żejt", "oil", "food"),
    ("ħall", "vinegar", "food"),
]

# Fix accidental leading space entry if any
A1_EXTRAS = [(w.strip(), g, c) for w, g, c in A1_EXTRAS if w.strip() and w.strip() != "mill-ġdid"]
A1_EXTRAS.append(("mill-ġdid", "again", "function"))
